package Vista;
import Modelo.Usuario;


public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnJugador = new javax.swing.JButton();
        btnEquipo = new javax.swing.JButton();
        btnPartido = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btnReporteEdadJugador = new javax.swing.JButton();
        btnReportPartidos = new javax.swing.JButton();
        btnGolesPorIDPartidoSimple = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnReporteJugadorEquipo = new javax.swing.JButton();
        btnReportePartidosFecha = new javax.swing.JButton();
        btnEquipoDTCiudad = new javax.swing.JButton();
        btnEquipoParticipacion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnReporPartidoComplejo = new javax.swing.JButton();
        btnRepoMaxIndices = new javax.swing.JButton();
        btnRepoGoleadores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido al menu de Gestión de Campeonatos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Gestión del sistema:");

        btnJugador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnJugador.setText("Jugador");
        btnJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugadorActionPerformed(evt);
            }
        });

        btnEquipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEquipo.setText("Equipo");
        btnEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipoActionPerformed(evt);
            }
        });

        btnPartido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPartido.setText("Partidos");
        btnPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Reportes:");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Reportes simples");

        btnReporteEdadJugador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReporteEdadJugador.setText("Jugadores Mayores a Edad Ingresada");
        btnReporteEdadJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteEdadJugadorActionPerformed(evt);
            }
        });

        btnReportPartidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReportPartidos.setText("Historial de Partidos");
        btnReportPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportPartidosActionPerformed(evt);
            }
        });

        btnGolesPorIDPartidoSimple.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGolesPorIDPartidoSimple.setText("Goles por ID de Partido");
        btnGolesPorIDPartidoSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGolesPorIDPartidoSimpleActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Reportes Intermedios");

        btnReporteJugadorEquipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReporteJugadorEquipo.setText("Jugadores de un Equipo");
        btnReporteJugadorEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteJugadorEquipoActionPerformed(evt);
            }
        });

        btnReportePartidosFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReportePartidosFecha.setText("Partidos por fechas");
        btnReportePartidosFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportePartidosFechaActionPerformed(evt);
            }
        });

        btnEquipoDTCiudad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEquipoDTCiudad.setText("Director y Ciudad de un Equipo");
        btnEquipoDTCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipoDTCiudadActionPerformed(evt);
            }
        });

        btnEquipoParticipacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEquipoParticipacion.setText("Participacion de un Equipo");
        btnEquipoParticipacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipoParticipacionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Reportes Complejos");

        btnReporPartidoComplejo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReporPartidoComplejo.setText("Reporte completo por partido");

        btnRepoMaxIndices.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRepoMaxIndices.setText("Equipos con Mayor Índice de Sanciones");

        btnRepoGoleadores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRepoGoleadores.setText("Maximo goleadores ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnPartido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(btnJugador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnReporteEdadJugador)
                                                    .addComponent(jLabel6)
                                                    .addComponent(btnReporPartidoComplejo))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(74, 74, 74)
                                                        .addComponent(btnRepoMaxIndices))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(89, 89, 89)
                                                        .addComponent(btnReportPartidos)))
                                                .addGap(142, 142, 142))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnReporteJugadorEquipo)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnReportePartidosFecha)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnEquipoDTCiudad)
                                                .addGap(85, 85, 85)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnEquipoParticipacion)
                                            .addComponent(btnRepoGoleadores)
                                            .addComponent(btnGolesPorIDPartidoSimple))))))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnJugador)
                                .addGap(18, 18, 18)
                                .addComponent(btnEquipo)
                                .addGap(18, 18, 18)
                                .addComponent(btnPartido))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnReporteEdadJugador)
                                    .addComponent(btnReportPartidos)
                                    .addComponent(btnGolesPorIDPartidoSimple))
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnReporteJugadorEquipo)
                                    .addComponent(btnReportePartidosFecha)
                                    .addComponent(btnEquipoDTCiudad)
                                    .addComponent(btnEquipoParticipacion))
                                .addGap(41, 41, 41)
                                .addComponent(jLabel6)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReporPartidoComplejo)
                            .addComponent(btnRepoMaxIndices)
                            .addComponent(btnRepoGoleadores))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidoActionPerformed
        // Boton -> Goles
        new VistaPartido().setVisible(true);
    }//GEN-LAST:event_btnPartidoActionPerformed

    private void btnJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugadorActionPerformed
        // Boton -> Jugador
        
        new VistaJugador().setVisible(true);
    }//GEN-LAST:event_btnJugadorActionPerformed

    private void btnReporteEdadJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteEdadJugadorActionPerformed
        // TODO add your handling code here:
        VistaReporSimpleEdadJugador vistaRepoEdadJugadores = new VistaReporSimpleEdadJugador();
        vistaRepoEdadJugadores.setVisible(true);
    }//GEN-LAST:event_btnReporteEdadJugadorActionPerformed

    private void btnReportPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportPartidosActionPerformed
        // TODO add your handling code here:
        VistaReportSimpleHoraPartido vistaReporHistorialPartidos = new VistaReportSimpleHoraPartido();
        vistaReporHistorialPartidos.setVisible(true);
    }//GEN-LAST:event_btnReportPartidosActionPerformed

    private void btnGolesPorIDPartidoSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGolesPorIDPartidoSimpleActionPerformed
        // TODO add your handling code here:
        VistaReportSimpleGolesPartido vistaReportGolesIDPartido = new VistaReportSimpleGolesPartido();
        vistaReportGolesIDPartido.setVisible(true);
    }//GEN-LAST:event_btnGolesPorIDPartidoSimpleActionPerformed

    private void btnReporteJugadorEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteJugadorEquipoActionPerformed
        // TODO add your handling code here:
        VistaReportIntermedioJugadoresEquipo vista = new VistaReportIntermedioJugadoresEquipo();
        vista.setVisible(true);
    }//GEN-LAST:event_btnReporteJugadorEquipoActionPerformed

    private void btnReportePartidosFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportePartidosFechaActionPerformed
        // TODO add your handling code here:
        VistaReportIntermedioPartidosFecha vista = new VistaReportIntermedioPartidosFecha();
        vista.setVisible(true);
    }//GEN-LAST:event_btnReportePartidosFechaActionPerformed

    private void btnEquipoDTCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipoDTCiudadActionPerformed
        // TODO add your handling code here:
        VistaReportIntermedioEquipoDTCiudad vista = new VistaReportIntermedioEquipoDTCiudad();
        vista.setVisible(true);
    }//GEN-LAST:event_btnEquipoDTCiudadActionPerformed

    private void btnEquipoParticipacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipoParticipacionActionPerformed
        // TODO add your handling code here:
        VistaReportIntermedioEquipoParticipacion vista = new VistaReportIntermedioEquipoParticipacion();
        vista.setVisible(true);
    }//GEN-LAST:event_btnEquipoParticipacionActionPerformed

    private void btnEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipoActionPerformed
        // TODO add your handling code here:
        VistaEquipo vista = new VistaEquipo();
        vista.setVisible(true);
    }//GEN-LAST:event_btnEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEquipo;
    private javax.swing.JButton btnEquipoDTCiudad;
    private javax.swing.JButton btnEquipoParticipacion;
    private javax.swing.JButton btnGolesPorIDPartidoSimple;
    private javax.swing.JButton btnJugador;
    private javax.swing.JButton btnPartido;
    private javax.swing.JButton btnRepoGoleadores;
    private javax.swing.JButton btnRepoMaxIndices;
    private javax.swing.JButton btnReporPartidoComplejo;
    private javax.swing.JButton btnReportPartidos;
    private javax.swing.JButton btnReporteEdadJugador;
    private javax.swing.JButton btnReporteJugadorEquipo;
    private javax.swing.JButton btnReportePartidosFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
