
package Vista;
import Modelo.Usuario;


public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JButton();
        btnJugador = new javax.swing.JButton();
        btnArbitro = new javax.swing.JButton();
        btnDirecTecnico = new javax.swing.JButton();
        btnEquipo = new javax.swing.JButton();
        btnGoles = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btnReporteEdadJugador = new javax.swing.JButton();
        btnReportPartidos = new javax.swing.JButton();
        btnGolesPorIDPartidoSimple = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnReporPartidoComplejo = new javax.swing.JButton();
        btnRepoEquipoMayorSaciones = new javax.swing.JButton();
        btnGoleadores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido al menu de Gestión de Campeonatos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Gestión del sistema:");

        btnUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUsuario.setText("Usuario");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        btnJugador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnJugador.setText("Jugador");
        btnJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugadorActionPerformed(evt);
            }
        });

        btnArbitro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnArbitro.setText("Arbitro");
        btnArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArbitroActionPerformed(evt);
            }
        });

        btnDirecTecnico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDirecTecnico.setText("Director Técnico");
        btnDirecTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirecTecnicoActionPerformed(evt);
            }
        });

        btnEquipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEquipo.setText("Equipo");

        btnGoles.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGoles.setText("Goles");
        btnGoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGolesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Reportes:");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Reportes simples");

        btnReporteEdadJugador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReporteEdadJugador.setText("Jugadores Mayores a Edad Ingresada");
        btnReporteEdadJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteEdadJugadorActionPerformed(evt);
            }
        });

        btnReportPartidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReportPartidos.setText("Historial de Partidos");
        btnReportPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportPartidosActionPerformed(evt);
            }
        });

        btnGolesPorIDPartidoSimple.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGolesPorIDPartidoSimple.setText("Goles por ID de Partido");
        btnGolesPorIDPartidoSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGolesPorIDPartidoSimpleActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Reportes Intermedios");

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("jButton4");

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("jButton5");

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("jButton6");

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("jButton7");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Reportes Complejos");

        btnReporPartidoComplejo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReporPartidoComplejo.setText("Información Completa de un Partido");
        btnReporPartidoComplejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporPartidoComplejoActionPerformed(evt);
            }
        });

        btnRepoEquipoMayorSaciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRepoEquipoMayorSaciones.setText("Equipos con Mayor Índice de Sanciones");
        btnRepoEquipoMayorSaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepoEquipoMayorSacionesActionPerformed(evt);
            }
        });

        btnGoleadores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGoleadores.setText("Máximos Goleadores y sus Equipos");
        btnGoleadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoleadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnGoles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEquipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDirecTecnico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(btnArbitro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnJugador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(123, 123, 123)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnReporteEdadJugador)
                                            .addComponent(jButton4)
                                            .addComponent(jLabel6)
                                            .addComponent(btnReporPartidoComplejo))
                                        .addGap(74, 74, 74)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton5)
                                            .addComponent(btnReportPartidos)
                                            .addComponent(btnRepoEquipoMayorSaciones))
                                        .addGap(89, 89, 89)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnGoleadores)
                                            .addComponent(btnGolesPorIDPartidoSimple)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton6)
                                                .addGap(61, 61, 61)
                                                .addComponent(jButton7))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(btnJugador)
                                .addGap(18, 18, 18)
                                .addComponent(btnArbitro)
                                .addGap(18, 18, 18)
                                .addComponent(btnDirecTecnico)
                                .addGap(18, 18, 18)
                                .addComponent(btnEquipo)
                                .addGap(18, 18, 18)
                                .addComponent(btnGoles))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnReporteEdadJugador)
                                    .addComponent(btnReportPartidos)
                                    .addComponent(btnGolesPorIDPartidoSimple))
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4)
                                    .addComponent(jButton5)
                                    .addComponent(jButton6)
                                    .addComponent(jButton7))
                                .addGap(41, 41, 41)
                                .addComponent(jLabel6)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReporPartidoComplejo)
                            .addComponent(btnRepoEquipoMayorSaciones)
                            .addComponent(btnGoleadores))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGolesActionPerformed
        // Boton -> Goles
        new VistaGoles().setVisible(true);
    }//GEN-LAST:event_btnGolesActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // Boton -> Usuario
        
        new VistaUsuario().setVisible(true);
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugadorActionPerformed
        // Boton -> Jugador
        
        new VistaJugador().setVisible(true);
    }//GEN-LAST:event_btnJugadorActionPerformed

    private void btnArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArbitroActionPerformed
        // Boton -> Arbitro
        
        new VistaArbitro().setVisible(true);
    }//GEN-LAST:event_btnArbitroActionPerformed

    private void btnDirecTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirecTecnicoActionPerformed
        // Boton -> Director Técnico
        
        new VistaDirecTecnico().setVisible(true);
    }//GEN-LAST:event_btnDirecTecnicoActionPerformed

    private void btnReporteEdadJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteEdadJugadorActionPerformed
        // TODO add your handling code here:
        VistaReporSimpleEdadJugador vistaRepoEdadJugadores = new VistaReporSimpleEdadJugador();
        vistaRepoEdadJugadores.setVisible(true);
    }//GEN-LAST:event_btnReporteEdadJugadorActionPerformed

    private void btnReportPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportPartidosActionPerformed
        // TODO add your handling code here:
        VistaReportSimpleHoraPartido vistaReporHistorialPartidos = new VistaReportSimpleHoraPartido();
        vistaReporHistorialPartidos.setVisible(true);
    }//GEN-LAST:event_btnReportPartidosActionPerformed

    private void btnGolesPorIDPartidoSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGolesPorIDPartidoSimpleActionPerformed
        // TODO add your handling code here:
        VistaReportSimpleGolesPartido vistaReportGolesIDPartido = new VistaReportSimpleGolesPartido();
        vistaReportGolesIDPartido.setVisible(true);
    }//GEN-LAST:event_btnGolesPorIDPartidoSimpleActionPerformed

    private void btnGoleadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoleadoresActionPerformed
        // TODO add your handling code here:
        
        VistaReportGoleadoresTop vistaReportGoleadoresTop = new VistaReportGoleadoresTop();
        vistaReportGoleadoresTop.setVisible(true);
    }//GEN-LAST:event_btnGoleadoresActionPerformed

    private void btnReporPartidoComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporPartidoComplejoActionPerformed
        // TODO add your handling code here:
        
        VistaReportPartidoComplejo vistaReportPartidoComplejo = new VistaReportPartidoComplejo();
        vistaReportPartidoComplejo.setVisible(true);
        
    }//GEN-LAST:event_btnReporPartidoComplejoActionPerformed

    private void btnRepoEquipoMayorSacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepoEquipoMayorSacionesActionPerformed
        // TODO add your handling code here:
        
        VistaReportEquipoSanciones vistaReportEquipoSanciones = new VistaReportEquipoSanciones();
        vistaReportEquipoSanciones.setVisible(true);
    }//GEN-LAST:event_btnRepoEquipoMayorSacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArbitro;
    private javax.swing.JButton btnDirecTecnico;
    private javax.swing.JButton btnEquipo;
    private javax.swing.JButton btnGoleadores;
    private javax.swing.JButton btnGoles;
    private javax.swing.JButton btnGolesPorIDPartidoSimple;
    private javax.swing.JButton btnJugador;
    private javax.swing.JButton btnRepoEquipoMayorSaciones;
    private javax.swing.JButton btnReporPartidoComplejo;
    private javax.swing.JButton btnReportPartidos;
    private javax.swing.JButton btnReporteEdadJugador;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
