package Vista;

import DAO.CiudadDAO;
import DAO.DBConnection;
import DAO.DirectorTecnicoDAO;
import DAO.EquipoDAO;
import Modelo.*;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VistaEquipo extends javax.swing.JFrame {

    public DirectorTecnicoDAO directorTecnicoDAO;
    public CiudadDAO ciudadDAO;
    Connection conn = DBConnection.conectar();
    /**
     * Creates new form VistaEquipo
     */
    public VistaEquipo() {
        initComponents();
        limpiarCampos();
        cargarDirectoresTecnicosComboBox();
        cargarCiudadesComboBox();
        cargarTablaEquipos();
        setLocationRelativeTo(null);
    }
    
    // Función que limpia los campos
    private void limpiarCampos() {
        txtIdEquipo.setText("");
        txtNombre.setText("");
        txtBuscarId.setText("");

        tablaRegistrosE.clearSelection();
    }
    
    // Carga el comboBox con los Directores Técnicos
    private void cargarDirectoresTecnicosComboBox() {
        try {
            directorTecnicoDAO = new DirectorTecnicoDAO(conn);
            List<DirectorTecnico> lista = directorTecnicoDAO.obtenerTodosLosDirectoresTecnicos();

            comboBoxDirectorTecnico.removeAllItems();

            for (DirectorTecnico dt : lista) {
                comboBoxDirectorTecnico.addItem(dt);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Carga el comboBox con las Ciudades
    private void cargarCiudadesComboBox() {
        try {
            ciudadDAO = new CiudadDAO(conn);
            List<Ciudad> ciudades = ciudadDAO.obtenerTodasLasCiudades();

            comboBoxCiudad.removeAllItems();

            for (Ciudad c : ciudades) {
                comboBoxCiudad.addItem(c);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Permite cargar los datos de los equipos en la tabla
    private void cargarTablaEquipos() {

        DefaultTableModel modelo = (DefaultTableModel) tablaRegistrosE.getModel();
        tablaRegistrosE.getTableHeader().setReorderingAllowed(false);
        modelo.setRowCount(0);

        EquipoDAO dao = new EquipoDAO(conn);
        List<Equipo> equipos = dao.obtenerEquipos();

        for (Equipo eq : equipos) {
            modelo.addRow(new Object[]{
                eq.getIdEquipo(),
                eq.getNombre(),
                eq.getDirectorTecnico_idUsuario(),
                eq.getCiudad_idCiudad()
            });
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdEquipo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        comboBoxDirectorTecnico = new javax.swing.JComboBox<>();
        comboBoxCiudad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtBuscarId = new javax.swing.JTextField();
        btnConsultarE = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRegistrosE = new javax.swing.JTable();
        btnGuardarE = new javax.swing.JButton();
        btnActualizarE = new javax.swing.JButton();
        btnEliminarE = new javax.swing.JButton();
        btnLimpiarE = new javax.swing.JButton();
        btnSalirE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Registro de Equipos");

        jLabel2.setText("N° Equipo:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Director Técnico:");

        jLabel5.setText("Ciudad:");

        txtIdEquipo.setEditable(false);

        jLabel8.setText("Consultar por ID:");

        btnConsultarE.setText("Consultar");
        btnConsultarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEActionPerformed(evt);
            }
        });

        tablaRegistrosE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "ID Director Técnico", "ID Ciudad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaRegistrosE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRegistrosEMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaRegistrosE);

        btnGuardarE.setText("Guardar");
        btnGuardarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEActionPerformed(evt);
            }
        });

        btnActualizarE.setText("Actualizar");
        btnActualizarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEActionPerformed(evt);
            }
        });

        btnEliminarE.setText("Eliminar");
        btnEliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEActionPerformed(evt);
            }
        });

        btnLimpiarE.setText("Limpiar");
        btnLimpiarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarEActionPerformed(evt);
            }
        });

        btnSalirE.setText("Salir");
        btnSalirE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1)
                        .addGap(0, 353, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnConsultarE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtBuscarId))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboBoxDirectorTecnico, 0, 244, Short.MAX_VALUE)
                                    .addComponent(comboBoxCiudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnGuardarE)
                                .addGap(10, 10, 10)
                                .addComponent(btnActualizarE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiarE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnSalirE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(10, 10, 10)
                                .addComponent(txtBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsultarE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtIdEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboBoxDirectorTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(comboBoxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarE)
                            .addComponent(btnActualizarE)
                            .addComponent(btnEliminarE)
                            .addComponent(btnLimpiarE))
                        .addGap(17, 17, 17)
                        .addComponent(btnSalirE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEActionPerformed
        // Botón de buscar (id)

        try {
            String idEquipoStr = txtBuscarId.getText().trim();

            if (idEquipoStr.isEmpty()) {
                JOptionPane.showMessageDialog(
                    this,
                    "Por favor, ingrese un ID válido para consultar.",
                    "Campo vacío",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            int idEquipo = Integer.parseInt(idEquipoStr);

            // Crear instancia del DAO
            EquipoDAO equipoDAO = new EquipoDAO(conn);

            // Consultar el equipo por ID
            Equipo equipo = equipoDAO.obtenerPorId(idEquipo);

            if (equipo != null) { // Si se encontró el equipo, llenar los campos

                txtIdEquipo.setText(String.valueOf(equipo.getIdEquipo()));
                txtNombre.setText(equipo.getNombre());

                // Seleccionar Director Técnico en ComboBox
                for (int i = 0; i < comboBoxDirectorTecnico.getItemCount(); i++) {
                    DirectorTecnico dt = (DirectorTecnico) comboBoxDirectorTecnico.getItemAt(i);

                    if (dt.getId_director_tecnico() == equipo.getDirectorTecnico_idUsuario()) {
                        comboBoxDirectorTecnico.setSelectedItem(dt);
                        break;
                    }
                }

                // Seleccionar Ciudad en ComboBox
                for (int i = 0; i < comboBoxCiudad.getItemCount(); i++) {
                    Ciudad ciudad = (Ciudad) comboBoxCiudad.getItemAt(i);

                    if (ciudad.getIdCiudad() == equipo.getCiudad_idCiudad()) {
                        comboBoxCiudad.setSelectedItem(ciudad);
                        break;
                    }
                }

                JOptionPane.showMessageDialog(
                    this,
                    "Equipo encontrado.",
                    "Consulta exitosa",
                    JOptionPane.INFORMATION_MESSAGE
                );

            } else {
                limpiarCampos();
                JOptionPane.showMessageDialog(
                    this,
                    "No se encontró ningún Equipo con ID: " + idEquipo,
                    "Equipo no encontrado",
                    JOptionPane.WARNING_MESSAGE
                );
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "El ID del equipo debe ser un número válido.",
                "Error de formato",
                JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnConsultarEActionPerformed

    private void btnGuardarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEActionPerformed
        try {
            // Obtener datos del formulario
            String nombre = txtNombre.getText().trim();
            DirectorTecnico dtSeleccionado = (DirectorTecnico) comboBoxDirectorTecnico.getSelectedItem();
            Ciudad ciudadSeleccionada = (Ciudad) comboBoxCiudad.getSelectedItem();

            // Validaciones simples
            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El nombre del equipo no puede estar vacío.");
                return;
            }
            if (dtSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un Director Técnico.");
                return;
            }
            if (ciudadSeleccionada == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una Ciudad.");
                return;
            }

            // Crear objeto Equipo
            Equipo equipo = new Equipo();
            equipo.setNombre(nombre);
            equipo.setDirectorTecnico_idUsuario(dtSeleccionado.getId_director_tecnico());
            equipo.setCiudad_idCiudad(ciudadSeleccionada.getIdCiudad());

            // Guardar en BD
            EquipoDAO equipoDAO = new EquipoDAO(conn);
            boolean exito = equipoDAO.registrarEquipo(equipo);

            if (exito) {
                JOptionPane.showMessageDialog(null, "Equipo registrado exitosamente.");
                cargarTablaEquipos();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Error al registrar el equipo.");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnGuardarEActionPerformed

    private void btnActualizarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEActionPerformed
        // Boton para actualizar datos del partido
        String idStr = txtIdEquipo.getText();
        if(idStr.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un equipo de la tabla para actualizar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        try {

            Equipo equipo = new Equipo();

            equipo.setIdEquipo(Integer.parseInt(txtIdEquipo.getText()));
            equipo.setNombre(txtNombre.getText());
            DirectorTecnico directorSeleccionado = (DirectorTecnico) comboBoxDirectorTecnico.getSelectedItem();
            equipo.setDirectorTecnico_idUsuario(directorSeleccionado.getId_director_tecnico());
            Ciudad ciudadSeleccionada = (Ciudad) comboBoxCiudad.getSelectedItem();
            equipo.setCiudad_idCiudad(ciudadSeleccionada.getIdCiudad());

            EquipoDAO equipoDAO = new EquipoDAO(conn);//conexion con la BD

            boolean actualizado = equipoDAO.actualizarEquipo(equipo);

            if(actualizado){
                JOptionPane.showMessageDialog(null, "Equipo actualizado exitosamente");
                cargarTablaEquipos();
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null, "Error al actualizar el equipo");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,"Error " + ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarEActionPerformed

    private void btnEliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEActionPerformed
        // Boton para eliminar algun registro que seleccione
        int fila = tablaRegistrosE.getSelectedRow();

        if(fila == -1){
            JOptionPane.showMessageDialog(null, "Seleccione un equipo a eliminar");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Esta seguro de eliminar este registro? ", "confirmar", JOptionPane.YES_NO_OPTION);
        int idEquipo = Integer.parseInt(tablaRegistrosE.getValueAt(fila, 0).toString());

        EquipoDAO equipoDAO = new EquipoDAO(conn);
        boolean eliminado = equipoDAO.eliminarEquipo(idEquipo);

        if(eliminado){
            JOptionPane.showMessageDialog(null, "Equipo eliminado correctamente");
            cargarTablaEquipos();//Actualiza la tabla
        }else{
            JOptionPane.showMessageDialog(null, "No se pudo eliminar el equipo");
        }
    }//GEN-LAST:event_btnEliminarEActionPerformed

    private void btnLimpiarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarEActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarEActionPerformed

    private void btnSalirEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirEActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirEActionPerformed

    private void tablaRegistrosEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRegistrosEMouseClicked
        // Detectar clic en una fila de la tabla de Equipos
        tablaRegistrosE.getSelectionModel().addListSelectionListener(e -> {

            if (!e.getValueIsAdjusting() && tablaRegistrosE.getSelectedRow() != -1) {

                int fila = tablaRegistrosE.getSelectedRow();

                // Llenar campos de texto
                txtNombre.setText(tablaRegistrosE.getValueAt(fila, 1).toString());

                // Seleccionar Director Técnico
                int idDT = Integer.parseInt(tablaRegistrosE.getValueAt(fila, 2).toString());
                for (int i = 0; i < comboBoxDirectorTecnico.getItemCount(); i++) {
                    DirectorTecnico dt = comboBoxDirectorTecnico.getItemAt(i);
                    if (dt.getId_director_tecnico() == idDT) {
                        comboBoxDirectorTecnico.setSelectedIndex(i);
                        break;
                    }
                }

                // Seleccionar Ciudad
                int idCiudad = Integer.parseInt(tablaRegistrosE.getValueAt(fila, 3).toString());
                for (int i = 0; i < comboBoxCiudad.getItemCount(); i++) {
                    Ciudad ciudad = comboBoxCiudad.getItemAt(i);
                    if (ciudad.getIdCiudad() == idCiudad) {
                        comboBoxCiudad.setSelectedIndex(i);
                        break;
                    }
                }

                // ID del equipo (para actualizar o eliminar)
                txtIdEquipo.setText(tablaRegistrosE.getValueAt(fila, 0).toString());
            }
        });
    }//GEN-LAST:event_tablaRegistrosEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarE;
    private javax.swing.JButton btnConsultarE;
    private javax.swing.JButton btnEliminarE;
    private javax.swing.JButton btnGuardarE;
    private javax.swing.JButton btnLimpiarE;
    private javax.swing.JButton btnSalirE;
    private javax.swing.JComboBox<Ciudad> comboBoxCiudad;
    private javax.swing.JComboBox<DirectorTecnico> comboBoxDirectorTecnico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaRegistrosE;
    private javax.swing.JTextField txtBuscarId;
    private javax.swing.JTextField txtIdEquipo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
