
package Vista;


import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import DAO.DBConnection;
import DAO.EquipoDAO;
import DAO.JugadorDAO;
import Modelo.Equipo;
import Modelo.Jugador;
import javax.swing.table.DefaultTableModel;


public class VistaJugador extends javax.swing.JFrame {
    
    public EquipoDAO equipoDAO;
    Connection conn = DBConnection.conectar();
    
    //Funcion que es usada para limpiar los campos
    private void limpiarCampos(){
        txtIdJugador.setText("");
        txtnombre1.setText("");
        txtNombre2.setText("");
        txtApellido1.setText("");
        txtApellido2.setText("");
        txtCedula.setText("");
        txtFechaN.setText("");
        txtContrato.setText("");
        txtNumCamiseta.setText("");
        comboBoxEq.setSelectedIndex(0);//seleccionar el primer estado
        
        //limpiar la seleccion de la fila seleccionada
        tablaRegistrosJ.clearSelection();   
    }
    
    /*Permite cargar el comboBox con el id y nombre de los equipos
    */
    private void cargarPartidosComboBox(){
        
        try {
            equipoDAO = new EquipoDAO(conn);
            List<Equipo> equipos = equipoDAO.obtenerTodos();
            comboBoxEq.removeAllItems();
            
            for(Equipo equipo: equipos)
                comboBoxEq.addItem(equipo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
       
    /*permite invocar las funciones del modelo para cargar los datos del jugador en la tabla
    */
    private void cargarTablaJugadores(){
        
        DefaultTableModel modelo = (DefaultTableModel) tablaRegistrosJ.getModel();
        tablaRegistrosJ.getTableHeader().setReorderingAllowed(false); //Para evitar que se puedan mover las columnas del Jtable
        modelo.setRowCount(0);
        
        JugadorDAO dao = new JugadorDAO(conn);
        List<Jugador> jugador = dao.obtenerJugadores();
        
        for(Jugador j : jugador){
            modelo.addRow(new Object[]{
             j.getId_jugador(),
             j.getNombreUno(),
             j.getNombreDos(),
             j.getApellidoUno(),
             j.getApellidoDos(),
             j.getCedula(),
             j.getFechaNacimiento(),
             j.getContrato(),
             j.getNumCamiseta(),
             j.getEquipo_idEquipo()
            });
        }
        
    }
    

    /**
     * Creates new form VistaJugador
     */
    public VistaJugador() {
        initComponents();
        cargarPartidosComboBox();
        cargarTablaJugadores();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtIdJugador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnombre1 = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        txtFechaN = new javax.swing.JTextField();
        txtContrato = new javax.swing.JTextField();
        btnGuardarJ = new javax.swing.JButton();
        btnActualizarJ = new javax.swing.JButton();
        btnEliminarj = new javax.swing.JButton();
        btnLimpiarJ = new javax.swing.JButton();
        btnSalirj = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtBuscarId = new javax.swing.JTextField();
        btnBuscarJ = new javax.swing.JButton();
        jScrollPanel = new javax.swing.JScrollPane();
        tablaRegistrosJ = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtNumCamiseta = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        comboBoxEq = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Registro de Jugadores");

        jLabel2.setText("N° Jugador:");

        jLabel3.setText("Primer Nombre:");

        txtNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Segundo Nombre:");

        jLabel5.setText("Apellido Uno:");

        jLabel6.setText("Apellido Dos:");

        jLabel7.setText("Cédula:");

        jLabel8.setText("Fecha Nacimiento:");

        jLabel9.setText("Duración del contrato:");

        btnGuardarJ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarJ.setText("Guardar");
        btnGuardarJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarJActionPerformed(evt);
            }
        });

        btnActualizarJ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizarJ.setText("Actualizar");

        btnEliminarj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarj.setText("Eliminar");

        btnLimpiarJ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiarJ.setText("Limpiar");
        btnLimpiarJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarJActionPerformed(evt);
            }
        });

        btnSalirj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalirj.setText("Salir");
        btnSalirj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirjActionPerformed(evt);
            }
        });

        jLabel10.setText("Consultar Jugador por ID: ");

        btnBuscarJ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarJ.setText("Consultar");

        tablaRegistrosJ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NombreUno", "NombreDos", "ApellidoUno", "ApellidoDos", "Cedula", "FechaNacimiento", "Contrato", "Camiseta", "Equipo"
            }
        ));
        tablaRegistrosJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRegistrosJMouseClicked(evt);
            }
        });
        jScrollPanel.setViewportView(tablaRegistrosJ);

        jLabel11.setText("Número de Camiseta:");

        jLabel12.setText("Lista de Equipos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel1)
                .addContainerGap(834, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(52, 52, 52)
                        .addComponent(txtnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(txtIdJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(39, 39, 39)
                                .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxEq, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumCamiseta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarJ)
                            .addComponent(jLabel10)
                            .addComponent(txtBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiarJ)
                                .addGap(32, 32, 32)
                                .addComponent(btnSalirj))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardarJ)
                        .addGap(29, 29, 29)
                        .addComponent(btnActualizarJ)
                        .addGap(33, 33, 33)
                        .addComponent(btnEliminarj)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPanel)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarJ))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtNumCamiseta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(comboBoxEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarJ)
                            .addComponent(btnActualizarJ)
                            .addComponent(btnEliminarj)
                            .addComponent(btnLimpiarJ)
                            .addComponent(btnSalirj)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPanel)))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2ActionPerformed

    private void btnSalirjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirjActionPerformed
        // Boton para salir
        this.dispose(); 
    }//GEN-LAST:event_btnSalirjActionPerformed

    private void btnLimpiarJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarJActionPerformed
        // Boton para limpiar campos, llamamos la funcion
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarJActionPerformed

    private void btnGuardarJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarJActionPerformed
        //boton para guardar los nuevos registros
        
    }//GEN-LAST:event_btnGuardarJActionPerformed

    private void tablaRegistrosJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRegistrosJMouseClicked
        // Para poder dar clic en alguna fila
        tablaRegistrosJ.getSelectionModel().addListSelectionListener(e ->{
        
        if (!e.getValueIsAdjusting() && tablaRegistrosJ.getSelectedRow() != -1){
            int fila = tablaRegistrosJ.getSelectedRow();
            
            
            txtnombre1.setText(tablaRegistrosJ.getValueAt(fila, 1).toString());
            txtNombre2.setText(tablaRegistrosJ.getValueAt(fila, 2).toString());
            txtApellido1.setText(tablaRegistrosJ.getValueAt(fila, 3).toString());
            txtApellido2.setText(tablaRegistrosJ.getValueAt(fila, 4).toString());
            txtCedula.setText(tablaRegistrosJ.getValueAt(fila, 5).toString());
            txtFechaN.setText(tablaRegistrosJ.getValueAt(fila, 6).toString());
            txtContrato.setText(tablaRegistrosJ.getValueAt(fila, 7).toString());
            txtNumCamiseta.setText(tablaRegistrosJ.getValueAt(fila, 8).toString());
            //seleccionar en el comboBox el estado correcto
            int idEquipo = Integer.parseInt(tablaRegistrosJ.getValueAt(fila, 9).toString());
            for (int i = 0; i < comboBoxEq.getItemCount(); i++){
                Equipo equipo = comboBoxEq.getItemAt(i);
                if (equipo.getIdEquipo() == idEquipo){
                    comboBoxEq.setSelectedIndex(i);
                    break;
                }
            }
            txtIdJugador.setText(tablaRegistrosJ.getValueAt(fila, 0).toString());// ID para actualizar
        }});
    }//GEN-LAST:event_tablaRegistrosJMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarJ;
    private javax.swing.JButton btnBuscarJ;
    private javax.swing.JButton btnEliminarj;
    private javax.swing.JButton btnGuardarJ;
    private javax.swing.JButton btnLimpiarJ;
    private javax.swing.JButton btnSalirj;
    private javax.swing.JComboBox<Equipo> comboBoxEq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaRegistrosJ;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtBuscarId;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtContrato;
    private javax.swing.JTextField txtFechaN;
    private javax.swing.JTextField txtIdJugador;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtNumCamiseta;
    private javax.swing.JTextField txtnombre1;
    // End of variables declaration//GEN-END:variables
}
