/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import DAO.DBConnection;
import DAO.JugadorDAO;
import Modelo.Jugador;
import Reportes.ReporteJugadoresMayores;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.*;

public class VistaReporSimpleEdadJugador extends javax.swing.JFrame {

    Connection conn = DBConnection.conectar();
    
    /**
     * Creates new form VistaReporSimpleEdadJugador
     */
    public VistaReporSimpleEdadJugador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtReporEdadJSimple = new javax.swing.JTextField();
        btnGenerarReporEdadJSimple = new javax.swing.JButton();
        btnVolverReporEdadJSimple = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Consulta Jugadores Mayores de Cierta Edad");

        jLabel2.setText("Ingrese edad: ");

        btnGenerarReporEdadJSimple.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGenerarReporEdadJSimple.setText("Generar");
        btnGenerarReporEdadJSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporEdadJSimpleActionPerformed(evt);
            }
        });

        btnVolverReporEdadJSimple.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolverReporEdadJSimple.setText("Volver");
        btnVolverReporEdadJSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverReporEdadJSimpleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtReporEdadJSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnGenerarReporEdadJSimple)
                        .addGap(44, 44, 44)
                        .addComponent(btnVolverReporEdadJSimple))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReporEdadJSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarReporEdadJSimple)
                    .addComponent(btnVolverReporEdadJSimple))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReporEdadJSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporEdadJSimpleActionPerformed
        // Boton para generar reporte
        try {
            int edad = Integer.parseInt(txtReporEdadJSimple.getText());
            JugadorDAO dao = new JugadorDAO(conn);
            List<Jugador> jugadores = dao.obtenerJugadoresMayoresA(edad);
            
            ReporteJugadoresMayores reporte = new ReporteJugadoresMayores();
            reporte.generarReporteJugadoresMayores(jugadores, edad);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese una edad válida_");
        }
        
        
    }//GEN-LAST:event_btnGenerarReporEdadJSimpleActionPerformed

    private void btnVolverReporEdadJSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverReporEdadJSimpleActionPerformed
        // Boton de volver
        this.dispose();
    }//GEN-LAST:event_btnVolverReporEdadJSimpleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaReporSimpleEdadJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaReporSimpleEdadJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaReporSimpleEdadJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaReporSimpleEdadJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaReporSimpleEdadJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReporEdadJSimple;
    private javax.swing.JButton btnVolverReporEdadJSimple;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtReporEdadJSimple;
    // End of variables declaration//GEN-END:variables
}
